### ISSUE TITLE
Display GO extensions on gene summary page and in GO tab

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#110]
There is  a> 4 year old issue that I will close
https://github.com/dictyBase/Migration/issues/10

Here is the new with dicty examples and how they should be displayed in GO tab and then on gene page.

### 1) GO tab
a) Gene: **_pde3_**
3',5'-cyclic-GMP phosphodiesterase activity, _activated_by_ (CHEBI:29035) | IDA | PMID...

Notes:
- Add the extension(s) after the term after a comma
- When > 1 extension, they are stored differently in the file, either separated by comma or by pipe. Please TRANSLATE into words. Comma means AND, | (pipe) means OR (see examples below)
- All database IDs should either link and pop up the name of the component as they do in QuickGO
- Relations such as 'activated_by', part_of' etc. are to be displayed in **italic** to set apart.

b) Gene **_gapA_**
protein localization to cleavage furrow, _part_of_ response to mechanical stimulus (GO:0009612) and _has_input_ (UniProtKB:P08799) | IMP | PMID ...

Note:
- The **and** after (GO:0009612) comes from a comma separating these two extensions in the file

c) **_dstA_**
positive regulation of gene expression, _has_regulation_target_ (UniProtKB:Q54EX0) or _has_regulation_target_ (UniProtKB:Q54DJ2) or _has_regulation_target_ (UniProtKB:Q54DJ1) | IMP | PMID...

Note:
- The **or** comes from the pipe | in the extensions

**Comment by pfey03** [comment]
2) Gene Summary Page

Here we display only the terms with extensions, as above and maybe add the 3-letter evidence code in parenthesis as the filtered terms will be listed line by line

**Molecular Function:**  
- 3',5'-cyclic-GMP phosphodiesterase activity, _activated_by_ (CHEBI:29035) (IDA)

**Biological Process:**  
-  protein localization to cleavage furrow, _part_of_ response to mechanical stimulus and _has_input_ **_mhcA_** (IMP)
 - positive regulation of gene expression, _has_regulation_target_ **_ecmF_** or _has_regulation_target_ _**ecmH**_ (IMP)

**Note here I translated UniProt IDs back to gene names!!**

**Comment by wildlifehexagon** [comment]
This has been finished and is live on `testdb`
