### ISSUE TITLE
Smart filtering GO for Display on Gene Summary Page

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#111]
This is the follow up from recent conversations and replaces
https://github.com/dictyBase/Migration/issues/107, which has some older ideas that now evolved.

Display of GO annotations on the Gene Summary Page is filtered for each GO Aspect (MF, BP and CC). So for each aspect, the following rules apply:

1) If EXP annotations are present -> Display NO Manual or IEA annotations

2) If no EXP are available BUT Manual -> Display Manual but NO IEAs

3) If no EXP and no Manual are available -> Display IEAs

4) For all evidence categories, EXP, Other Manual, and IEAs, **display only 5 most recent annotations** 

5) Display: 
GO term + extension| With | Evidence

Here are some real annotations for gene _svkA_ and how they should be listed on Gene Summary Page

### Molecular Function:
protein serine/threonine kinase activity (IDA)
protein kinase activity _has_input_ sevA (IDA
protein binding  _with_ cepL (IPI)

### Biological Process:
protein phosphorylation _has_input_ sevA (IDA)
regulation of actin cytoskeleton organization (IMP)
positive regulation of cell division (IMP)

### Cellular Component:
cytoplasm _exists_during_ mitotic interphase (IDA)
centromere _exists_during_ mitotic cytokinesis (IDA)

All extensions and also the 'with' in italic. All Dicty genes in extensions like here cepL and sevA, should be linked to those genes.

**Comment by wildlifehexagon** [comment]
This has been finished and is live on `testdb`
