### ISSUE TITLE
Gene name links on gene page should not be case sensitive

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#114]
Currently when i insert a gene name instead the ID for example like here, it works
https://testdb.dictybase.org/gene/tgrC1/goannotations

But https://testdb.dictybase.org/gene/tgrc1/goannotations does NOT work and I get server error. It shouldn't be case sensitive!

Thanks,
Petra

**Comment by wildlifehexagon** [comment]
Closing this since I have opened it [here](https://github.com/dictyBase/Genomepage/issues/67)
