### ISSUE TITLE
Limit Strain/Phenotype display on Gene summary page and Tab design

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#122]
When there is a lot of strain and phenotype data, the section on the gene summary page can be too big, and we need to create tabs on Phenotype tab
http://dictybase.org/gene/tgrC1
1. Gene Summary Page
Create a rule, like for GO just different:
- display only 6 (not 5 as in GO) strains with phenotypes
- display the first knockout strain, thus the one with earliest paper. In the above example it's tgrC1- /DBS0235461. Or if looking for the paper date is too complicated: look for the gene name with a hyphen, like tgrC1- and choose the one with MOST phenotypes.

2. Phenotype tab should become: Strain and Phenotypes
a. Display all strains with phenotypes like it is currently including DSC availability
b. Include another tab that enlists those strains that don't have phenotypes which for the above example are a lot. Add DSC availability here as well

As context, strains 2.b. without phenotypes are often annotated because they are in the DSC, but there are also a few that have been annotated over the years for other reasons and either the available strain was lost or they have a citation but no phenotype annotated.

Many thanks!!

**Comment by wildlifehexagon** [comment]
closing this since it has been connected to the proper repository -- https://github.com/dictyBase/Genomepage/issues/80
