### ISSUE TITLE
display DD anatomy term names not IDs in GO

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#123]
See for example EXP annotations of this gene:
https://testdb.dictybase.org/gene/DDB_G0287317/goannotations

In the CC section you see the extension to 
'nucleus' _part of_ (DDANAT:0000405)

It should be:
'nucleus' _part of_ prespore cell

The DDANAT ontology is here:
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo

Thanks!

**Comment by pfey03** [comment]
Ah and the anatomy terms could link to the EBI Ontology Lookup Service, see is linking to that would work:
https://www.ebi.ac.uk/ols/ontologies/ddanat/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDDANAT_0000405

The link is ugly but the page is nice. Or for a simpler link and ok page this:
 http://purl.obolibrary.org/obo/DDANAT_0000405

Thanks,
Petra

**Comment by wildlifehexagon** [comment]
closing this -- let's use this issue https://github.com/dictyBase/Genomepage/issues/79
