### ISSUE TITLE
GO page has wrong CC header

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#137]
I just noticed, guess never looked carefully at headers, that the section for GO is wrongly called 'Cellular Composition' but it should be called **Cellular Component** on the GO annotation page. 
https://testdb.dictybase.org/gene/cln3/goannotations

On the Gene Page it is correct:
https://testdb.dictybase.org/gene/cln3

Please fix on all GO pages before release!!

**Comment by erichartline** [comment]
fixed in latest [update](https://github.com/dictyBase/genomepage/commit/b4270dc37487bc4e5ba9b3bb2af3b7403efb33af)
