### ISSUE TITLE
can't link gene with newly added paper

### ISSUE THREAD

**Issue by rjdodson** [dictyBase/Migration#33]
Hi Petra:

Thanks for this link. Looks like two of these are older papers-epublished
in Dec. 2014 and identified by the script then. Two are new which I added
with the curation tool with the option to add new papers.

However, I was not able to link a gene to one of the papers (the other had
no genes), and I’m not sure if this is a consequence of having added the
reference with the curation tool (as opposed to having the script add it).
I am trying to add the gene mrps4 to reference:

http://dictybase.org/curation/reference/14527

Sidd, let me know if this is an issue I should add to Github, and if so,
which repository.

Thanks,
Bob

**Comment by pfey03** [comment]
I just tried with a paper that came in by script last week (PMID 25653647) and attach the sadA gene, and that didn't work, so this is VERY HIGH URGENCY or paper curation ist toast now.

**Comment by pfey03** [comment]
This is the error message: ( can't see any link, it's a pop up window on this page: http://dictybase.org/curation/reference/14506

"There was a problem serving the page

Now, if you are wondering what to do now ?. Well .....

Try refreshing the page, the problem might be temporary
Check the url is correct
We have been notified about the problem and will do our best to make sure it doesn't happen again
Please come back after a while, the problem might be solved by that time
And of course please feel free to e-mail us at dictybase@northwestern.edu"

**Comment by pfey03** [comment]
It is not just ADDING A GENE, we can also not ADD ANY TOPIC to an existing attached gene, so the whole tool is broken.

BTW, that error is the same we get nowadays for the fast track gene curation tool when we enter an ID to curate. I always figured the new GBrowse might have broken that tool and it’s not serious not to have that as we are done. However, I hope this doesn’t mark the early end of the paper curation tool!

**Comment by pfey03** [comment]
fixed
