### ISSUE TITLE
Stock Center Data Migration

### ISSUE THREAD

**Issue by biodavidjm** [dictyBase/Migration#37]
1. Export data: Check that everything has been exported

   - [x] Check that the numbers matches between the [SQL](https://github.com/dictyBase/Migration/blob/master/stock-data-migration/export.md) and the outputs from modware-dump
   - [x] Revise SQL statements and Perl code.    

2. Import data:
   - [ ] Is anything missed?

**Comment by cybersiddhu** [comment]
#31
