### ISSUE TITLE
Resource and data specifications for cv module of chado

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Migration#46]

**Comment by cybersiddhu** [comment]
![cvterm_model_for_data_api](https://cloud.githubusercontent.com/assets/48740/14930927/2c3bb4ca-0e2d-11e6-824c-caad8b61f239.png)

**Comment by pfey03** [comment]
pretty!

**Comment by cybersiddhu** [comment]
![cvterm_data_model_rel](https://cloud.githubusercontent.com/assets/48740/14989359/03f5d142-111d-11e6-98b8-834a37453577.png)

**Comment by cybersiddhu** [comment]
#31
