### ISSUE TITLE
Import strain properties

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Migration#59]
#55
#31

**Comment by cybersiddhu** [comment]
#55

**Comment by cybersiddhu** [comment]
Hi @pfey03 @rjdodson
Here is the csv[txt] file for importing strain properties where the value of second column should be a term of a defined ontology. However, i couldn't find any ontology that contains those term.
So, in order to load those data either you could define a new ontology or you could include them in any of our defined ontology. The new or updated ontology should be kept in our [migration-data](https://github.com/dictyBase/migration-data/tree/master/ontologies) repository.

cc: @wildlifehexagon 
[strain_props.txt](https://github.com/dictyBase/Migration/files/3267043/strain_props.txt)

**Comment by pfey03** [comment]
@cybersiddhu, the second column is the name of the field and two are ontologies, the others are names and free text or ID added automatically.:

- synonym: The synonym name / free text
- systematic name: added manually or DDB Id is added automatically if empty
- mutagenesis method: ontology https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_mutagenesis_method.obo
- mutant type: genetic modification ontology https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_genetic_modification.obo

Does that clarify?

**Comment by pfey03** [comment]
@cybersiddhu 
Do you want me to add the terms

- synonym
- systematic name

to the dicty_annotation.obo?

**Comment by pfey03** [comment]
@cybersiddhu 
make sure you map **mutant type** to dicty_genetic_modification.obo

It was historically named mutant type by Jakob and eric implemented. But we corrected it when creating the ontology

**Comment by cybersiddhu** [comment]
alright, thanks for the clarifications and yes please add them to dicty_annotation.obo

**Comment by pfey03** [comment]
Add only the se 2 terms?

- synonym
- systematic name

I'm near the end here and soon off until coming to Chicago so please confirm @cybersiddhu

**Comment by cybersiddhu** [comment]
Yes `synonym` and `systematic name`

**Comment by pfey03** [comment]
thanks

**Comment by pfey03** [comment]
I noticed 'strain descriptor' is also not in ontology, is that ok?

**Comment by cybersiddhu** [comment]
sure

**Comment by pfey03** [comment]
adding or not adding? Sorry for the bad question

**Comment by pfey03** [comment]
@cybersiddhu  ok, added 3 new terms including 'strain descriptor' and committed to Git

**Comment by cybersiddhu** [comment]
[strainprop-20190812-211654.log](https://github.com/dictyBase/Migration/files/3494427/strainprop-20190812-211654.log)
Here is the current log which loads all of the data.

**Comment by cybersiddhu** [comment]
Still keeping it open because the loader is not correctly handling multiple synonyms per strain.

**Comment by cybersiddhu** [comment]
Current log
[strainsyn-20190822-023729.log](https://github.com/dictyBase/Migration/files/3530523/strainsyn-20190822-023729.log)
