### ISSUE TITLE
Dicty Azkaban

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Migration#64]
I never heard of it, what is `Dicty Azkaban` ?
https://github.com/dictyBase/Modware-Loader/blob/v1.8.14/lib/Modware/Import/Stock/StrainImporter.pm#L570
Currently it is being used to create plasmid entries that are not real plasmid. The issue is [here](https://github.com/dictyBase/Modware-Loader/issues/63).

@pfey03 
@haridusenadeera 
@ypandit 

#61

**Comment by haridusenadeera** [comment]
Maybe this helps? 
http://dictybase.github.io/stock-data-import/

> ## Strain-Plasmid
> 
> - Strains have plasmids associated with it. Some of these plasmids are available in the Dicty StockCenter, while some are not.
> - The plasmids that are not currently available in the Stock Center, may or may not be available in the future. Thus, we use the same data model as the one’s available. The only difference is `stockcollection.name => 'Dicty Azkaban'`
> - If ever, these plasmids are made available we can change `stockcollection.name => Dicty Stockcenter`

**Comment by cybersiddhu** [comment]
Thanks haridu, yeah i have seen that, but  i don't understand using a separate name. Whatever entries we have should belong to `Dicty Stockcenter` whether that entity is present in the freezer or not.  For example, we do have strain entries that are not available in stock center for ordering.  We use **inventories** for distinguishing their availability. 
And for the sake of argument, if we do separate non-physical entities, the name could have been different , say `Dicty Virtual Stockcenter`,  `Dicty Virtual entries`, something that semantically makes sense. 
@rjdodson

**Comment by cybersiddhu** [comment]
And since it made it to the database, it's magical effects are creating all sorts of import errors.

Point to remember that, i get virtually no error in data export where this entry is absent.

**Comment by pfey03** [comment]
seems like Yogesh called the not matching plasmid store 'Azkaban'. Never heard the name before. But yes, it's free text and while we now always add plasmids that are listed in the DSC plasmid list, we still have a ton (Jakob) legacy. I fix them when I come across them but we have no systematic way. If you want to create a list I might be able to work with Lina on it.
@LinaFouad

**Comment by cybersiddhu** [comment]
After more thought, even though a strain/plasmid not present physically in the **Dicty stock center**, it does exist physically somewhere in the planet in some lab. So, we could add it to a collection/name where it is currently now. However, for bulk import of data, that assignment is not possible, so we have choose something default that makes sense. So, what it could be ..
* [ ] Other dicty lab
* [ ] External laboratory
* [ ] Others: Please give me suggestion in that case.

Later on, we could open up this field in the interface, to add a proper source name for the non-available entry and then change it back explicitly or whenever they have an inventory.

**Comment by pfey03** [comment]
'External laboratory' reflects it quite well, especially for the annotated strains not in the DSC. With plasmids, it's mostly a free text issue, and a minority would be external lab. As I said, we now add plasmid only if we have it and all the different resistance cassettes created to KO genes, we entered dummy plasmids for that purpose that are NOT in the DSC:
http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=839
http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=902
http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=840
http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=845

**Comment by pfey03** [comment]
For database purpose of course, we can also add all the non matching plasmids external laboratory. But what about the 4 we added and are not available? Also external laboratory? The latter rather match the strains in the database that are added to curate phenotypes and are not in the DSC but annotated
