### ISSUE TITLE
merged two terms in dicty_strain_characteristics.obo

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#77]
I merged two strain characteristic terms:
DDSTRAINCHAR:0000018 was merged with DDSTRAINCHAR:0000011, the latter is the primary term.

1) in the current dictybase the file is still called 'strain_characteristics.obo', but in the new and here in Git we have  dicty_strain_characteristics.obo to be consistent. I updated both.

2) In the current database, the curation tool displays it correctly, and only the primary term shows up in the strain characteristics list, so this is good. However, in the annotations, they did not get auto fixed like if I change something in phenotype ontology. This ontology doesn't 'talk back' to the current database. 

In sum,It's not a big deal that annotations currently do not reflect the change, but I hope and think it will get fixed when migrated to new database. 
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_strain_characteristics.obo

**Comment by cybersiddhu** [comment]
#90
