### ISSUE TITLE
GO display 2: separate IEAs from manual annotations on Gene Summary page

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#8]
When there are a lot of GO annotations, especially for conserved genes, there are too many annotations bunched together and in no sense making order. Often there are IEAs for exactly the same terms that we have already as IDA or such. 
http://dictybase.org/gene/p2xA
SGD separates them, and even finer as they also mark 'high throughput', which we don't have. They show only manual annotations on the gene summary, and all annotations including IEAs on the GO page/tab
http://www.yeastgenome.org/cgi-bin/locus.fpl?locus=S000000011
http://www.yeastgenome.org/cgi-bin/locus.fpl?locus=S000000011/go

We don't have such deep annotations in Dicty, so we wouldn't have any annotations for some if we don't show IEAs on Summary page. But I like their one annotation per line and bullet point organization. Much easier to see the annotations. I can probably come up with a mock-up at some point, but comments from others appreciated.

**Comment by wildlifehexagon** [comment]
I believe this can be closed now since we have decided to only show most recent annotations on the gene summary page. Feel free to reopen if I'm misinterpreting.

**Comment by pfey03** [comment]
we should have an algorithm that shows EXP if available, Manual next and Automatic last up to 5 most recent in that order. Need to see if there is an issue about it, there should be

**Comment by pfey03** [comment]
https://github.com/dictyBase/Migration/issues/111 also closed already. Is algorithm to sort EXP>Man>Auto in place?

**Comment by wildlifehexagon** [comment]
Yes - that logic is already on `testdb`

**Comment by pfey03** [comment]
OK then I close this one again, thanks!
