### ISSUE TITLE
DSC Order Form: Make phone numbers required

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#87]
Currently the phone numbers on the Order form for Shipping and Payment are not required. But for example Fedex requires a phone number for shipping, so please make it mandatory, at least on the Shipping form.
It can stay as is on the Payment part of form, but it wouldn't matter either way.

Thanks!

@cybersiddhu @el-komandante

**Comment by wildlifehexagon** [comment]
This was fixed in 60ce669266f9fdc8a7583d72ef39edfed5810345
