### ISSUE TITLE
Issue with strain characteristics

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Migration#90]
The strain characteristics `temperature conditional mutant` is not getting imported as it is synonym rather than a primary term. The export script need to change it to `temperature sensitive mutant` during the export.

**Comment by cybersiddhu** [comment]
#31

**Comment by pfey03** [comment]
Updated all 79 annotations with DDSTRAINCHAR:0000018 ‘temperature conditional mutant’ to DDSTRAINCHAR:0000011 ‘temperature sensitive mutant’, the primary term in the current ontology.

Now the current ontology should match all annotations.

**Comment by cybersiddhu** [comment]
Have to confirm with an export-import

**Comment by cybersiddhu** [comment]
#55

**Comment by cybersiddhu** [comment]
Current log
[strainchar-20190812-205919.log](https://github.com/dictyBase/Migration/files/3494544/strainchar-20190812-205919.log)

All the records were loaded.
