### ISSUE TITLE
delete spaces in genotypes

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#96]
In the past several years, we conformed more to standard genotypes and one of the format rules are that there are no spaces after a comma and each statement. Here are two genotypes, one with spaces and one without.

* With Spaces (WRONG)
axeA1, axeB1, axeC1, cycA1, tsgA1, acrD369, ebrB364, sprH351, manA1, tmpA600, carB-[carB-thy], thy+, [ecmB]:lacZ, neoR

* NO Spaces (CORRECT)
axeA1,axeB1,axeC1,cycA1,tsgA1,acrD369,ebrB364,sprH351,manA1,tmpA600,carB-[carB-thy],thy+,[act15]:GFP,neoR

So if possible, automatically delete the spaces after comma in genotypes
Thanks!

**Comment by cybersiddhu** [comment]
#55
