### ISSUE TITLE
format genotypes properly

### ISSUE THREAD

**Issue by pfey03** [dictyBase/Migration#99]
Genotypes are typically formatted in italics, except the drug resistance(s) at the end.

Like this:
*_axeA1,axeB1,axeC1,dimB-,[bsRcas]_,bsR
*_axeA2,axeB2,axeC2,rrpB-,rrpC-,lacZ,[pDneo2a],RNAi-lacZ_,neoR,bsR

Can you do that automatic formatting?
Thanks!

**Comment by cybersiddhu** [comment]
#55

**Comment by cybersiddhu** [comment]
This is something that has to be done in the front end
